### ISSUE TITLE
Data refresh rate is very low

### ISSUE THREAD

**Issue by bitfindm** [RUB-SysSec/DroneSecurity#11]
I tried, and it was far less than 640 milliseconds per data.Can you help me with this?

**Comment by mrlnc** [comment]
The receiver cannot detect & decode *every* frame, because it does not perform any error correction, handling of poor RF quality, and such. You could verify that the data is being *send* with very high rate by capturing the raw IQ samples, open it with `inspectrum`, and measure the time between DroneID frames.

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
