### ISSUE TITLE
C2 and beacon packets

### ISSUE THREAD

**Issue by gcarmix** [RUB-SysSec/DroneSecurity#22]
First of all congratulations for your job,
I'm doing some research on drone communication and I noticed on your software that you refer also to c2 and beacon packets.
I also noticed that the code part for those packets is at very early stages.
I'd like to know from you, if possible, something more about c2 and beacon packets.

In my captures I often find this kind of packets that are bigger than 2 MHz in bandwidth and last for about 500us. (attached here)   Are these ones the C2 packets? (if so I think we should correct the bandwidth in your code since it is slighlty smaller)
![unknown_pkt](https://github.com/RUB-SysSec/DroneSecurity/assets/7345884/0d369fdf-11b6-4517-8fe8-9f68c70e53c3)
If not, could you provide some samples, or at least a screenshot of what should we expect (for C2 and Beacons)?

Thank you!

**Comment by nschllr** [comment]
Hi, thanks a lot!
I named the packets that I wasn't able to identify 'beacons.' The C2 packets should be around 1.5MHz wide, but we haven't examined them in more detail. You can limit the used frequency bands in the drone's settings so that it only uses the 2.4GHz band. If you do this and capture while the remote is connected, you should be able to spot the C2 packets in inspectrum. At this stage, our code is not able to use or process these packets, and I haven't tested if it can store them correctly. However, you can try setting the live receiver to these packets, and if it finds a packet, it will be stored in a file called 'ext_droneid_{sample_rate}.

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
